---
- name: Create directory tree inventory
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Install required packages
      become: yes
      apt:
        name: tree
        state: present

    - name: Get the base directory name
      command: basename "{{ playbook_dir }}"
      register: base_dir_name

    - name: Run tree command to get directory structure
      command: tree -H . -L 2
      register: tree_output
      args:
        chdir: "{{ playbook_dir }}"

    - name: Write tree output to markdown file
      copy:
        dest: "{{ playbook_dir }}/{{ base_dir_name.stdout }}_inventory.md"
        content: |
          # Inventory of {{ base_dir_name.stdout }}
          
          {{ tree_output.stdout }}
